In [1]:
import pandas as pd

from utils.wrangle import wrangle

df = pd.read_csv('data/commodity_prices.csv')
df = wrangle(df)

Seasonal Index Calculation

In [2]:
# 1. Calculate average price per product & season
seasonal_avg = (
    df.groupby(['Product_Type', 'Season'])['Modal_Price']
      .mean()
      .reset_index(name='Seasonal_avg_price')
    )
# Get overall mean per product
overall_mean = (
    df.groupby('Product_Type')['Modal_Price']
      .mean()
      .reset_index()
      .rename(columns={'Modal_Price': 'Overall_Mean'})
)

# Merge overall mean into seasonal averages
seasonal_avg = seasonal_avg.merge(overall_mean, on='Product_Type')

# Calculate seasonal index
seasonal_avg['Seasonal_Index'] = (
    seasonal_avg['Seasonal_avg_price'] / seasonal_avg['Overall_Mean']
)

seasonal_avg.head(10)

,Product_Type,Season,Seasonal_avg_price,Overall_Mean,Seasonal_Index
0,Alsandikai|Alsandikai|FAQ,Post Monsoon,4239.583333,4302.123142,0.985463
1,Alsandikai|Alsandikai|FAQ,Southwest Monsoon,4732.666667,4302.123142,1.100077
2,Alsandikai|Alsandikai|FAQ,Summer,3620.422535,4302.123142,0.841543
3,Alsandikai|Alsandikai|FAQ,Winter,4570.992366,4302.123142,1.062497
4,Amaranthus|Amaranthus|FAQ,Post Monsoon,3415.929204,3307.963488,1.032638
5,Amaranthus|Amaranthus|FAQ,Southwest Monsoon,3294.165946,3307.963488,0.995829
6,Amaranthus|Amaranthus|FAQ,Summer,3236.073620,3307.963488,0.978268
7,Amaranthus|Amaranthus|FAQ,Winter,3342.164675,3307.963488,1.010339
8,Amaranthus|Other|FAQ,Post Monsoon,3719.444444,4015.775862,0.926208
9,Amaranthus|Other|FAQ,Southwest Monsoon,3898.917749,4015.775862,0.970900

Yearly Effect Calcualtion

In [3]:
yearly_avg = (
    df.groupby(['Product_Type', 'Market', 'Season', 'Year'])['Modal_Price']
    .mean()
    .reset_index(name='Yearly_avg_price')
)

overall_avg = (
    df.groupby(['Product_Type', 'Market', 'Season'])['Modal_Price']
    .mean()
    .reset_index(name='Overall_avg_price')
)

yearly_avg = yearly_avg.merge(overall_avg, on=['Product_Type', 'Market', 'Season'])
yearly_avg['Yearly_Index'] = (
    yearly_avg['Yearly_avg_price'] / yearly_avg['Overall_avg_price']
)

yearly_avg.head(10)

,Product_Type,Market,Season,Year,Yearly_avg_price,Overall_avg_price,Yearly_Index
0,Alsandikai|Alsandikai|FAQ,North Paravur,Post Monsoon,2024,4239.583333,4239.583333,1.000000
1,Alsandikai|Alsandikai|FAQ,North Paravur,Southwest Monsoon,2024,4794.565217,4732.666667,1.013079
2,Alsandikai|Alsandikai|FAQ,North Paravur,Southwest Monsoon,2025,4634.482759,4732.666667,0.979254
3,Alsandikai|Alsandikai|FAQ,North Paravur,Summer,2024,3684.507042,3620.422535,1.017701
4,Alsandikai|Alsandikai|FAQ,North Paravur,Summer,2025,3556.338028,3620.422535,0.982299
5,Alsandikai|Alsandikai|FAQ,North Paravur,Winter,2023,4746.153846,4570.992366,1.038320
6,Alsandikai|Alsandikai|FAQ,North Paravur,Winter,2024,4556.944444,4570.992366,0.996927
7,Alsandikai|Alsandikai|FAQ,North Paravur,Winter,2025,4543.478261,4570.992366,0.993981
8,Amaranthus|Amaranthus|FAQ,Aluva,Post Monsoon,2023,4480.769231,4707.070707,0.951923
9,Amaranthus|Amaranthus|FAQ,Aluva,Post Monsoon,2024,4957.446809,4707.070707,1.053191

In [ ]:
model = smf.

# Get market ranking
fe_params = result.fe_params
market_ranking = fe_params.filter(like='C(Market)')
market_ranking.index = market_ranking.index.str.replace('C(Market)[T.', '').str.replace(']', '')
market_ranking['Aluva'] = 0  # Add Aluva as baseline
market_ranking.sort_values(ascending=True, inplace=True)
print(market_ranking)

In [ ]:
df.groupby('Product_Type')['Market'].nunique().sort_values(ascending=False)